[package]
name = "pagecache"
version = "0.12.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "lock-free pagecache and log for high-performance databases"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled/tree/master/crates/pagecache"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/pagecache/"
readme = "README.md"
edition = "2018"

[features]
default = []
compression = ["zstd"]
lock_free_delays = ["rand", "rand_hc"]
failpoints = ["fail", "rand"]
no_metrics = ["historian/bypass"]
no_logs = ["log/max_level_off"]
nightly = []
no_inline = []
event_log = []
measure_allocs = []

[dependencies]
crossbeam-utils = "0.6.5"
crossbeam-epoch = "0.7"
bincode = "1.0"
fs2 = "0.4"
fxhash = "0.2"
futures = "0.1"
hashbrown = { version = "0.1", features = ["serde"] }
lazy_static = "1.2"
libc = "0.2"
rayon = "1.0"
zstd = { version = "0.4", optional = true }
fail = { version = "0.2", optional = true }
rand = { version = "0.6", optional = true }
rand_hc = { version = "0.1", optional = true }
crc32fast = "1.1.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.historian]
version = "3.0"

[dependencies.log]
version = "0.4"

[dev-dependencies]
rand = "0.6"
model = "0.1"
