[package]
name = "pagecache"
version = "0.6.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "lock-free pagecache and log for high-performance databases"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled/tree/master/crates/pagecache"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/pagecache/"
readme = "README.md"

[features]
default = []
lock_free_delays = ["rand"]
failpoints = ["fail"]
no_metrics = ["historian/bypass"]
no_logs = ["log/max_level_off"]
nightly = []
no_inline = []

[dependencies]
libc = "0.2"
crossbeam-epoch = "0.6"
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.1"
fail = {version = "0.2", optional = true}
rayon = "1.0"
zstd = {version = "0.4", optional = true}
rand = {version = "0.5", optional = true}
pagetable = {version = "0.0", path = "../pagetable"}

[dependencies.historian]
version = "3.0"

[dependencies.log]
version = "0.4"

[dev-dependencies]
rand = "0.5"
