[package]
name = "pagecache"
version = "0.7.7"
authors = ["Tyler Neely <t@jujit.su>"]
description = "lock-free pagecache and log for high-performance databases"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled/tree/master/crates/pagecache"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/pagecache/"
readme = "README.md"
edition = "2018"

[features]
default = []
lock_free_delays = ["sled_sync/lock_free_delays"]
failpoints = ["fail", "rand"]
no_metrics = ["historian/bypass"]
no_logs = ["_log/max_level_off"]
nightly = ["sled_sync/nightly"]
no_inline = ["sled_sync/no_inline"]
event_log = []
measure_allocs = []
compression = ["zstd"]

[dependencies]
libc = "0.2"
bincode = "1.0"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.2"
rayon = "1.0"
fs2 = "0.4"
pagetable = { version = "0.1", path = "../pagetable" }
sled_sync = { version = "0.1", path = "../sled_sync" }
zstd = { version = "0.4", optional = true }
fail = { version = "0.2", optional = true }
rand = { version = "0.6", optional = true }

[dependencies.historian]
version = "3.0"

[dependencies._log]
package = "log"
version = "0.4"

[dev-dependencies]
rand = "0.6"
