[package]
name = "stress2"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
publish = false

[profile.release]
debug = 2

[features]
default = []
lock_free_delays = ["sled/lock_free_delays"]
check_snapshot_integrity = ["sled/check_snapshot_integrity"]
rayon = ["sled/rayon"]
zstd = ["sled/zstd"]
no_logs = ["sled/no_logs"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
docopt = "1.0"
chan-signal = "0.3"
rand = "0.4"
sled = { path = "../../crates/sled" }
