language: rust

sudo: required

cache: cargo

rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: TEST=clippy
    - rust: nightly-2018-01-02
      env:
        - TEST=tsan
        - RUSTFLAGS="-Z sanitizer=thread"
    - rust: nightly-2018-01-02
      env:
        - TEST=lsan
        - RUSTFLAGS="-Z sanitizer=leak"
    - rust: nightly-2018-01-02
      env:
        - TEST=crash
        - RUST_BACKTRACE=1

script:
  - bash -c 'case "$TEST" in
               clippy)
                 cargo test --features="clippy"
                 ;;
               lsan)
                 sudo cargo run -p stress2 --release --target x86_64-unknown-linux-gnu
                 ;;
               tsan)
                 cargo run -p stress2 --features=lock_free_delays --release --target x86_64-unknown-linux-gnu
                 ;;
               crash)
                 cargo test test_crash_recovery --release --features="check_snapshot_integrity" -- --nocapture
                 ;;
               *)
                 cargo check;
                 cargo check --features=zstd;
                 cargo check --features=rayon;
                 cargo check --features=zstd,rayon;
                 cargo test
                 ;;
             esac'

os:
  - linux
  - osx
