language: rust

sudo: required

cache:
  cargo: true
  directories:
    - ~/.rustup

install:
  - curl https://sh.rustup.rs -sSf |
    sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION &&
    rustup component add clippy-preview
  - if [ -n "$TARGET" ]; then
        rustup target add $TARGET;
    fi
  - source ~/.cargo/env

matrix:
  include:
    - os: linux
      rust: nightly-2018-10-26
      env:
        - TEST=sanitizers
    - os: linux
      rust: nightly-2018-10-26
      env:
        - TEST=cross-build
        - TARGET=i686-unknown-linux-gnu
    - os: osx
      rust: stable
      env:
        - TEST=osx
    - os: linux
      rust: stable
      env:
        - TEST=standard
    - os: linux
      rust: stable
      env:
        - TEST=crash
        - RUST_BACKTRACE=1
    - os: linux
      rust: stable
      env:
        - TEST=qc_log
    - os: linux
      rust: stable
      env:
        - TEST=qc_pagecache
    - os: linux
      rust: stable
      env:
        - TEST=qc_tree
    - os: linux
      rust: stable
      env:
        - TEST=clippy
        - RUSTFLAGS=-Dwarnings
  allow_failures:
    - os: linux
      rust: stable
      env:
        - TEST=clippy
        - RUSTFLAGS=-Dwarnings

script:
  - bash -c 'case "$TEST" in
               osx)
                 pushd tests &&
                 cargo check &&
                 cargo check --features=all &&
                 cargo test test_crash_recovery --release -- --ignored &&
                 cargo test tree --release
                 ;;
               qc_log)
                 pushd tests &&
                 cargo test quickcheck_log_works --release -- --ignored
                 ;;
               qc_pagecache)
                 pushd tests &&
                 cargo test quickcheck_pagecache_works --release -- --ignored
                 ;;
               qc_tree)
                 pushd tests &&
                 cargo test quickcheck_tree_matches_btreemap --release -- --ignored
                 ;;
               clippy)
                 cargo clippy
                 ;;
               sanitizers)
                 echo "lsan" &&
                 cargo clean -p stress2 &&
                 cargo clean -p sled_sync &&
                 cargo clean -p pagecache &&
                 cargo clean -p pagetable &&
                 cargo clean -p sled &&
                 export RUSTFLAGS="-Z sanitizer=leak" &&
                 cargo build --features=lock_free_delays,no_jemalloc --target x86_64-unknown-linux-gnu &&
                 sudo target/x86_64-unknown-linux-gnu/debug/stress2 --duration=30 &&

                 echo "asan" &&
                 cargo clean -p stress2 &&
                 cargo clean -p sled_sync &&
                 cargo clean -p pagecache &&
                 cargo clean -p pagetable &&
                 cargo clean -p sled &&
                 export RUSTFLAGS="-Z sanitizer=address" &&
                 cargo build --features=lock_free_delays,no_jemalloc --target x86_64-unknown-linux-gnu &&
                 sudo target/x86_64-unknown-linux-gnu/debug/stress2 --duration=30 &&

                 echo "tsan" &&
                 cargo clean -p stress2 &&
                 cargo clean -p sled_sync &&
                 cargo clean -p pagecache &&
                 cargo clean -p pagetable &&
                 cargo clean -p sled &&
                 export RUSTFLAGS="-Z sanitizer=thread" &&
                 export TSAN_OPTIONS=suppressions=/home/travis/build/spacejam/sled/tsan_suppressions.txt &&
                 cargo run --features=lock_free_delays,no_jemalloc --target x86_64-unknown-linux-gnu -- --duration=30
                 ;;
               lsan)
                 pushd benchmarks/stress2 &&
                 ;;
               tsan)
                 pushd benchmarks/stress2;
                 ;;
               crash)
                 pushd tests &&
                 cargo test test_crash_recovery --release -- --nocapture --ignored
                 ;;
               cross-build)
                 echo "https://github.com/rust-lang/cargo/issues/4753";
                 pushd crates/sled; cargo build --target $TARGET --features=nightly && popd &&
                 pushd crates/pagecache && cargo build --target $TARGET --features=nightly && popd
                 ;;
               standard)
                 pushd tests &&
                 cargo check &&
                 cargo check --features=all &&
                 popd &&
                 cargo test --release
                 ;;
               concurrent)
                 cargo test concurrent --release -- --ignored
                 ;;
               *)
                 echo "unknown TEST value \"$TEST\"";
                 exit 1
                 ;;
             esac'
