language: rust

sudo: required

cache: cargo

rust:
  - stable
  - beta

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: TEST=clippy
    - rust: nightly-2017-10-19
      env: TEST=tsan
    - rust: nightly-2017-10-19
      env: TEST=lsan

script:
  - bash -c 'case "$TEST" in
               clippy)
                 cargo test --features="clippy"
                 ;;
               lsan)
                 ./hack/leak_detector
                 ;;
               tsan)
                 ./hack/race_detector
                 ;;
               *)
                 cargo check;
                 cargo check --features=zstd;
                 cargo check --features=rayon;
                 cargo check --features=zstd,rayon;
                 cargo test
                 ;;
             esac'

os:
  - linux
  - osx
