language: rust

sudo: required

cache: cargo

rust:
  - stable

env: # important hack for allow_failures below. this also enables the default build!

matrix:
  include:
    - os: linux
      rust: nightly-2018-09-13
      env:
        - TEST=tsan
        - RUSTFLAGS="-Z sanitizer=thread"
        - TSAN_OPTIONS=suppressions=/home/travis/build/spacejam/sled/tsan_suppressions.txt
    - os: linux
      rust: nightly-2018-09-13
      env:
        - TEST=lsan
        - RUSTFLAGS="-Z sanitizer=leak"
    - os: linux
      rust: nightly-2018-09-13
      env:
        - TEST=crash
        - RUST_BACKTRACE=1
    - os: linux
      rust: nightly-2018-09-13
      env:
        - TEST=cross-build
        - TARGET=i686-unknown-linux-gnu
    - os: osx
      env:
        - TEST=osx
  allow_failures:
    - os: linux
      env:
        - TEST=clippy
        - RUSTFLAGS=-Dwarnings

install:
  - curl https://sh.rustup.rs -sSf |
    sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION;
    rustup component add clippy-preview
  - if [ -n "$TARGET" ]; then
        rustup target add $TARGET;
    fi
  - source ~/.cargo/env

script:
  - bash -c 'case "$TEST" in
               osx)
                 cargo check;
                 cargo check --features=all
                 ;;
               clippy)
                 cargo clippy
                 ;;
               lsan)
                 cd benchmarks/stress2;
                 cargo build --target x86_64-unknown-linux-gnu;
                 sudo target/x86_64-unknown-linux-gnu/debug/stress2
                 ;;
               tsan)
                 cd benchmarks/stress2;
                 cargo run --features=lock_free_delays --target x86_64-unknown-linux-gnu
                 ;;
               crash)
                 cargo test test_crash_recovery --release --features="check_snapshot_integrity" -- --nocapture
                 ;;
               cross-build)
                 echo "https://github.com/rust-lang/cargo/issues/4753";
                 pushd crates/sled; cargo build --target $TARGET --features=nightly; popd;
                 pushd crates/pagecache; cargo build --target $TARGET --features=nightly; popd
                 ;;
               *)
                 cargo check;
                 cargo check --features=all;
                 cargo test --release
                 ;;
             esac'
