language: rust

sudo: required

cache: cargo

rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: TEST=clippy
    - rust: nightly-2018-01-02
      env: TEST=tsan
    - rust: nightly-2018-01-02
      env: TEST=lsan
    - rust: nightly-2018-01-02
      env: TEST=crash

script:
  - bash -c 'case "$TEST" in
               clippy)
                 cargo test --features="clippy"
                 ;;
               lsan)
                 ./hack/leak_detector
                 ;;
               tsan)
                 ./hack/race_detector
                 ;;
               crash)
                 cargo test test_crash_recovery --release --features="check_snapshot_integrity" -- --nocapture
                 ;;
               *)
                 cargo check;
                 cargo check --features=zstd;
                 cargo check --features=rayon;
                 cargo check --features=zstd,rayon;
                 cargo test
                 ;;
             esac'

os:
  - linux
  - osx
