[package]
name = "rsdb"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "transactional KV store backed by a log-structured persistent B+ tree"
license = "Apache-2.0"
homepage = "https://github.com/spacejam/rsdb"
keywords = ["database", "embedded", "high-performance", "persistent", "transaction"]

[[test]]
name = "test"
path = "test/test.rs"

[dependencies]
rustc-serialize = "0.3"
bincode = "0.6"
libc = "0.2"

[dev-dependencies]
quickcheck = "0.2"
rand = "0.3"
