[package]
name = "sled"
version = "0.15.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "a flash-sympathetic persistent lock-free B+ tree, pagecache, and log"
license = "Apache-2.0"
homepage = "https://github.com/spacejam/sled"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/sled/"
readme = "README.md"

[features]
default = []
profiler = ["stress", "cpuprofiler"]
bench = ["clap", "num_cpus", "rand", "chrono", "rayon", "zstd", "env_logger"]
stress = ["docopt", "chan-signal", "rayon", "rand"]
o_direct_writer = []

[profile.release]
debug = 2

[[bin]]
name = "bench"
required-features = ["bench"]

[[bin]]
name = "stress"
required-features = ["stress"]

[[bin]]
name = "stress2"
required-features = ["stress"]

[dependencies.historian]
version = "3.0"
# features = ["bypass"]

[dependencies.log]
version = "0.3"
# features = ["max_level_off"]

[dependencies]
coco = "0.2"
bincode = "0.8"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "0.2"
rayon = {version = "0.8", optional = true}
env_logger = {version = "0.4", optional = true}
num_cpus = {version = "1.6", optional = true}
zstd = {version = "0.4", optional = true}
clippy = {version = "0.0", optional = true}
clap = {version = "2.26", optional = true}
rand = {version = "0.3", optional = true}
docopt = {version = "0.8", optional = true}
chan-signal = {version = "0.3", optional = true}
chrono = {version = "0.4", optional = true}
cpuprofiler = {version = "0.0.3", optional = true}

[dev-dependencies]
quickcheck = "0.2"
libc = "0.2"
rand = "0.3"
