[package]
name = "rsdb"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "dead simple persistent kv store"
license = "Apache-2.0"
homepage = "https://github.com/spacejam/rsdb"
keywords = ["database", "embeddable", "kv", "persistent"]
