[workspace]
members = [
  "crates/pagecache",
  "crates/sled",
  "bindings/sled-native",
  "tests"
]
exclude = [
  "crates/deterministic",
  "crates/model",
  "crates/simulator",
  "benchmarks/stress2",
  "examples/pessimistic_transactions",
  "examples/crdt_merge_store",
]
