[package]
name = "sled"
version = "0.15.4"
authors = ["Tyler Neely <t@jujit.su>"]
description = "a flash-sympathetic persistent lock-free B+ tree"
license = "MIT/Apache-2.0"
homepage = "https://github.com/spacejam/sled"
repository = "https://github.com/spacejam/sled"
keywords = ["database", "embedded", "concurrent", "persistent", "lock-free"]
documentation = "https://docs.rs/sled/"
readme = "../../README.md"

[features]
default = []
lock_free_delays = []

[profile.release]
debug = 2

[dependencies.log]
version = "0.4"
# features = ["max_level_off"]

[dependencies]
crossbeam-epoch = "0.4"
bincode = "0.9"
serde = "1.0"
serde_derive = "1.0"
clippy = {version = "0.0", optional = true}
pagecache = { path = "../pagecache", version = "0.2.2" }
